# 9.Data 어떻게 표현하면 좋을까? 배열(array)과 표(table)

## 9.2 평균 계산하기

### 평균 계산하기

In [1]:
total = 0
count = 0
numbers = input("Enter a number :  (<Enter Key> to quit)")
while numbers != "":
    try:
        x = float(numbers)
        count += 1
        total = total + x
    except ValueError:
        print('NOT a number! Ignored..')
    numbers = input("Enter a number :  (<Enter Key> to quit)")
avg = total / count
print("\n average is", avg)

Enter a number :  (<Enter Key> to quit)1
Enter a number :  (<Enter Key> to quit)4
Enter a number :  (<Enter Key> to quit)6
Enter a number :  (<Enter Key> to quit)

 average is 3.6666666666666665


## 9.3 배열을 활용한 평균, 표준편차, 중앙값 계산

### 사용자가 입력한 숫자들을 배열로 만들기

In [3]:
def numbers():
    X = []
    while True:
        number = input("숫자를 입력하시오: (엔터키를 누르면 정지)")
        while number != "":
            try:
                x = float(number)
                X.append(x)
            except ValueError:
                print('>>> not a number!')
            number = input("숫자를 입력하시오: (엔터키를 누르면 정지)")
        if len(X) > 1:
            return X
X = numbers()

print('X:' , X)

숫자를 입력하시오: (엔터키를 누르면 정지)3
숫자를 입력하시오: (엔터키를 누르면 정지)A
>>> not a number!
숫자를 입력하시오: (엔터키를 누르면 정지)5
숫자를 입력하시오: (엔터키를 누르면 정지)6
숫자를 입력하시오: (엔터키를 누르면 정지)
X: [3.0, 5.0, 6.0]


- 파이썬 리스트는 동적 배열!

### list와 array이의 차이

In [4]:
import array as arr

mylist = [1, 2, 3]   # 이것은 파이썬 built-in list입니다. 
print(type(mylist))

mylist.append('4')  # mylist의 끝에 character '4'를 추가합니다. 
print(mylist)

mylist.insert(1, 5)  # mylist의 두번째 자리에 5를 끼워넣습니다.
print(mylist)

myarray = arr.array('i', [1, 2, 3])   # 이것은 array입니다. import array를 해야 쓸 수 있습니다.
print(type(myarray))

# 아래 라인의 주석을 풀고 실행하면 에러가 납니다.
#myarray.append('4')    # myarray의 끝에 character '4'를 추가합니다. 
print(myarray)

myarray.insert(1, 5)    # myarray의 두번째 자리에 5를 끼워넣습니다.
print(myarray)

<class 'list'>
[1, 2, 3, '4']
[1, 5, 2, 3, '4']
<class 'array.array'>
array('i', [1, 2, 3])
array('i', [1, 5, 2, 3])


- list 안의 element 사이에 다른 타입의 자료형이 허용
- array는 처음부터 element의 유형을 지정해서 생성하며, 지정되지 않은 다른 타입의 element 추가가 허용되지 않는다

### 리스트를 활용한 시그마의 표현

In [5]:
total = 0.0
for i in range(len(X)):
    total = total + X[i]
mean = total / len(X)

print('sum of X: ', total)

sum of X:  14.0


### 중앙값
- n이 홀수이면 n/2을 반올림한 순서의 값이 중앙값
- n이 짝수라면 n/2번째 값과 ((n/2) + 1) 번째 값의 평균

In [8]:
def median(nums):
    nums.sort()
    size = len(nums)
    p = size // 2
    if size % 2 == 0:
        pr = p
        pl = p-1
        mid = float((nums[pl] + nums[pr]) / 2)
    else:
        mid = nums[p]
    
    return mid

print('X: ',X)
median(X)

X:  [3.0, 5.0, 6.0]


5.0

### 표준편차와 평균

In [9]:
# 평균

def means(nums):
    total = 0.0
    for i in range(len(nums)):
        total += nums[i]
    return total / len(nums)

means(X)

4.666666666666667

In [10]:
# 표준편차

avg = means(X)

def std_dev(nums, avg):
    texp = 0.0
    for i in range(len(nums)):
        texp += (nums[i] - avg) ** 2
    return (texp / len(nums)) ** 0.5

std_dev(X, avg)

1.247219128924647

### 전체 코드 : main() 함수

In [11]:
def numbers():                             # 리스트 입력받기
    X=[]
    while True:
        number = input("Enter a number (<Enter key> to quit)") 
        while number !="":
            try:
                x = float(number)
                X.append(x)
            except ValueError:
                print('>>> NOT a number! Ignored..')
            number = input("Enter a number (<Enter key> to quit)")
        if len(X) > 1:
            return X

def median(nums):                           # 평균
    nums.sort()
    size = len(nums)
    p = size // 2
    if size % 2 == 0:
        pr = p
        pl = p-1
        mid = float((nums[pl]+nums[pr])/2)
    else:
        mid = nums[p]
    return mid

def means(nums):                            # 중앙값
    total = 0.0
    for i in range(len(nums)):
        total = total + nums[i]
    return total / len(nums)

def std_dev(nums, avg):                    # 표준편차
   texp = 0.0
   for i in range(len(nums)):
       texp = texp + (nums[i] - avg) ** 2
   return (texp/len(nums)) ** 0.5

def main():
    X = numbers()
    med = median(X)
    avg = means(X)
    std = std_dev(X, avg)
    print("당신이 입력한 숫자{}의 ".format(X))
    print("중앙값은{}, 평균은{}, 표준편차는{}입니다.".format(med, avg, std))

if __name__ == '__main__':
    main()

Enter a number (<Enter key> to quit)3
Enter a number (<Enter key> to quit)5
Enter a number (<Enter key> to quit)9
Enter a number (<Enter key> to quit)21
Enter a number (<Enter key> to quit)34
Enter a number (<Enter key> to quit)1
Enter a number (<Enter key> to quit)
당신이 입력한 숫자[1.0, 3.0, 5.0, 9.0, 21.0, 34.0]의 
중앙값은7.0, 평균은12.166666666666666, 표준편차는11.724854891307707입니다.


## 9.4 Numpy 소개

- 과학 계산용 고성능 컴퓨팅과 데이터 분석에 필요한 파이썬 패키지
- pip install numpy
- 빠르고 메모리를 효율적으로 사용하여 벡터의 산술 연산과 브로드캐스팅 연산을 지원하는 다차원 배열 ndarray 데이터 타입을 지원
- 반복문을 작성할 필요 없이 전체 데이터 배열에 대해 빠른 연산을 제공하는 다양한 표준 수학 함수를 제공
- 배열 데이터를 디스크에 쓰거나 읽을 수 있다

## 9.5 NumPy의 주요 기능

### 1) ndarray 만들기

In [2]:
import numpy as np

# 아래 A와 B는 결과적으로 같은 ndarray 객체를 생성합니다. 
A = np.arange(5)
B = np.array([0,1,2,3,4])  # 파이썬 리스트를 numpy ndarray로 변환

# 하지만 C는 좀 다를 것입니다. 
C = np.array([0,1,2,3,'4'])

# D도 A, B와 같은 결과를 내겠지만, B의 방법을 권합니다. 
D = np.ndarray((5,), np.int64, np.array([0,1,2,3,4]))

print(A)
print(type(A))
print("--------------------------")
print(B)
print(type(B))
print("--------------------------")
print(C)
print(type(C))
print("--------------------------")
print(D)
print(type(D))

[0 1 2 3 4]
<class 'numpy.ndarray'>
--------------------------
[0 1 2 3 4]
<class 'numpy.ndarray'>
--------------------------
['0' '1' '2' '3' '4']
<class 'numpy.ndarray'>
--------------------------
[0 1 2 3 4]
<class 'numpy.ndarray'>


- numpy.ndarray도 array이므로 모든 element의 type이 동일해야 한다.
- 숫자는 모두 문자열로 바꿔 줄 수 있어서 C가 전부 문자열로

### 2) 크기
- ndarray.size : 행렬 내 원소의 개수
- ndarray.shape : 행렬의 모양
- ndarray.ndim : 행렬의 축의 개수 
- reshape() : 행렬의 모양을 바꿔줌

In [13]:
A = np.arange(10).reshape(2, 5)   # 길이 10의 1차원 행렬을 2X5 2차원 행렬로 바꿔봅니다.

print("행렬의 모양:", A.shape)
print("행렬의 축 개수:", A.ndim)
print("행렬 내 원소의 개수:", A.size)

행렬의 모양: (2, 5)
행렬의 축 개수: 2
행렬 내 원소의 개수: 10


In [15]:
A = np.arange(10).reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [3]:
A = np.arange(10)
print("A : "  ,A)
B = np.arange(10).reshape(2,5)
print("B  :" ,B )
C = np.arange(10).reshape(3,3) # 에러가 남
print("C  : ", C)

A :  [0 1 2 3 4 5 6 7 8 9]
B  : [[0 1 2 3 4]
 [5 6 7 8 9]]


ValueError: cannot reshape array of size 10 into shape (3,3)

### 3) type
- NumPy: numpy.array.dtype
- 파이썬: type()

In [19]:
A= np.arange(6).reshape(2, 3)
print(A)
print(A.dtype)
print(type(A))
print("-------------------------")

B = np.array([0, 1, 2, 3, 4, 5])  
print(B)
print(B.dtype)
print(type(B))
print("-------------------------")

C = np.array([0, 1, 2, 3, '4', 5])
print(C)
print(C.dtype)
print(type(C))
print("-------------------------")

D = np.array([0, 1, 2, 3, [4, 5], 6])  # 이런 ndarray도 만들어질까요?
print(D)
print(D.dtype)
print(type(D))

[[0 1 2]
 [3 4 5]]
int64
<class 'numpy.ndarray'>
-------------------------
[0 1 2 3 4 5]
int64
<class 'numpy.ndarray'>
-------------------------
['0' '1' '2' '3' '4' '5']
<U21
<class 'numpy.ndarray'>
-------------------------
[0 1 2 3 list([4, 5]) 6]
object
<class 'numpy.ndarray'>


/tmp/ipykernel_13/130055213.py:19: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  D = np.array([0, 1, 2, 3, [4, 5], 6])  # 이런 ndarray도 만들어질까요?


- dtype은 NumPy ndarray의 "원소"의 데이터 타입을 반환
- 파이썬 내장함수인 type(A)을 이용하면 행렬 A의 자료형이 반환
- D.dtype은 object를 리턴. 파이썬의 최상위 클래스는 바로 object

In [20]:
D = np.array([0, 1, 2, 3, [4, 5], 6], dtype=object)  # warning 메시지를 보고 이렇게 바꿔봅니다.
print(D)
print(D.dtype)
print(type(D))

[0 1 2 3 list([4, 5]) 6]
object
<class 'numpy.ndarray'>


In [21]:
C = np.array([0,1,2,3,'4',5])
print(C[0])
print(type(C[0]))
print(C[4])
print(type(C[4]))
print("------------------------------")

D = np.array([0,1,2,3,[4,5],6], dtype=object)
print(D[0])
print(type(D[0]))
print(D[4])
print(type(D[4]))

0
<class 'numpy.str_'>
4
<class 'numpy.str_'>
------------------------------
0
<class 'int'>
[4, 5]
<class 'list'>


### 4) 특수 행렬
- 단위행렬
- 0 행렬
- 1 행렬

In [22]:
# 단위행렬
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# 0행렬
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
# 1행렬
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 5) 브로드캐스트

In [25]:
A = np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
A * 2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [27]:
A + 2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [29]:
# 3 X 3 행렬에 1 X 3 행렬을 더했을 때
A = np.arange(9).reshape(3,3)
B = np.array([1,2,3])

print("A : ", A)
print("B : ", B)
print('A+B : ', A+B)

A :  [[0 1 2]
 [3 4 5]
 [6 7 8]]
B :  [1 2 3]
A+B :  [[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]


In [31]:
# 3 X 3 행렬에 3 X 1 행렬을 더했을 때
A = np.arange(9).reshape(3,3)
C = np.array([[1],[2],[3]])

print("A : ", A)
print("C : ", C)
print('A+C : ', A+C)

A :  [[0 1 2]
 [3 4 5]
 [6 7 8]]
C :  [[1]
 [2]
 [3]]
A+C :  [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


In [32]:
# 3 X 3 행렬에 1 X 2 행렬을 더하는 것은 허용되지 않는다
A = np.arange(9).reshape(3,3)
D = np.array([1,2])
A + D

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [33]:
print([1,2]+[3,4])
print([1,2]+3)

[1, 2, 3, 4]


TypeError: can only concatenate list (not "int") to list

In [34]:
print(np.array([1,2])+np.array([3,4]))
print(np.array([1,2])+3)

[4 6]
[4 5]


### 6) 슬라이스와 인덱싱

In [41]:
# 3 x 3 행렬의 첫번째 행 구하기
A = np.arange(9).reshape(3,3)
print("A: ", A)
B = A[0]
print("B: ", B)

A:  [[0 1 2]
 [3 4 5]
 [6 7 8]]
B:  [0 1 2]


In [43]:
A[:-1]

array([[0, 1, 2],
       [3, 4, 5]])

In [44]:
A[:,2:]

array([[2],
       [5],
       [8]])

In [51]:
A[:,1:]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [52]:
A[:,:]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
A[:,-1:]

array([[2],
       [5],
       [8]])

In [54]:
A[:,-2:]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [55]:
A[1,:2]

array([3, 4])

In [56]:
A[:2,1:]

array([[1, 2],
       [4, 5]])

In [57]:
A[:,-1]

array([2, 5, 8])

### 7) random
- np.random.randint()
- np.random.choice()
- np.random.permutation()
- np.random.normal()
- np.random.uniform()

In [59]:
# 0-1 사이의 난수 생성
np.random.random()

0.9980413261646722

In [61]:
# 0과 9 사이의 정수형 난수 생성
np.random.randint(0,10)

8

In [62]:
# 리스트에 주어진 값 중 하나를 랜덤으로 
np.random.choice([0,1,2,3,4,5,6,7,8])

1

In [63]:
# 무작위로 섞인 배열을 만들어 줍니다. 
# 아래 2가지는 기능면에서 동일합니다. 

print(np.random.permutation(10))   
print(np.random.permutation([0,1,2,3,4,5,6,7,8,9]))

[8 7 0 2 4 3 1 6 9 5]
[4 1 5 9 7 6 8 3 0 2]


In [64]:
# 아래 기능들은 어떤 분포를 따르는 변수를 임의로 표본추출해 줍니다. 

# 이것은 정규분포를 따릅니다.
print(np.random.normal(loc=0, scale=1, size=5))    # 평균(loc), 표준편차(scale), 추출개수(size)를 조절해 보세요.

# 이것은 균등분포를 따릅니다. 
print(np.random.uniform(low=-1, high=1, size=5))  # 최소(low), 최대(high), 추출개수(size)를 조절해 보세요.

[-0.2205125   1.28976024 -0.17143924 -0.05459393  0.8055235 ]
[ 0.9968567  -0.97317289 -0.1746778  -0.1542494   0.59608959]


### 8) 전치행렬
- arr.T: 행렬의 행과 열 맞바꾸기
- np.transpose: 축을 기준으로 행렬의 행과 열 바꾸기

In [66]:
A = np.arange(24).reshape(2,3,4)
A

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [67]:
A.T

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [68]:
A.T.shape

(4, 3, 2)

In [69]:
# np.transpose는 행렬의 축을 어떻게 변환해 줄지 임의로 지정해 줄 수 있는 일반적인 행렬 전치 함수

In [70]:
B = np.transpose(A, (2,0,1))

In [71]:
B

array([[[ 0,  4,  8],
        [12, 16, 20]],

       [[ 1,  5,  9],
        [13, 17, 21]],

       [[ 2,  6, 10],
        [14, 18, 22]],

       [[ 3,  7, 11],
        [15, 19, 23]]])

In [72]:
A = np.array([[1,2,3], [4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## 9.6 NumPy로 기본 통계 데이터 계산해 보기

In [74]:
import numpy as np

def numbers():
    X = []
    number = input("Enter a number (<Enter key> to quit)") 
    # 하지만 2개 이상의 숫자를 받아야 한다는 제약조건을 제외하였습니다.
    while number != "":
        try:
            x = float(number)
            X.append(x)
        except ValueError:
            print('>>> NOT a number! Ignored..')
        number = input("Enter a number (<Enter key> to quit)")
    return X

def main():
    nums = numbers()       # 이것은 파이썬 리스트입니다. 
    num = np.array(nums)   # 리스트를 Numpy ndarray로 변환합니다.
    print("합", num.sum())
    print("평균값",num.mean())
    print("표준편차",num.std())
    print("중앙값",np.median(num))   # num.median() 이 아님에 유의해 주세요.

main()

Enter a number (<Enter key> to quit)2
Enter a number (<Enter key> to quit)4
Enter a number (<Enter key> to quit)6
Enter a number (<Enter key> to quit)1
Enter a number (<Enter key> to quit)23
Enter a number (<Enter key> to quit)
합 36.0
평균값 7.2
표준편차 8.084553172563094
중앙값 4.0


In [75]:
A = np.array([1,2,3,4,5])

In [76]:
A.sum()

15

In [77]:
A.mean()

3.0

In [78]:
A.std()

1.4142135623730951